### ISSUE TITLE
Duplicate hammer.js loading issue

### ISSUE THREAD

**Issue by big-kahuna-burger** [Vyrent/front_end#7]
I'm not sure how this resolves.

If I do `typings i` with current setup, typing for hammer.js gets globally installed, but then again there is node_modules/@types/hammerjs also installed because of package.json dependency.

I would need @amirsabersharifi 's advice on this.

**Comment by amirsabersharifi** [comment]
there is nothing wrong with this. I believe microsoft is doing something on here to bring dependencies to the npm itself and use those. but all that matters for now is if you point tsconfig to use which dependency, and as long as you are using typings(for now) it's good enough.
